version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Xmx3200m
      TERM: dumb
      ANDROID_HOME: /opt/android/sdk

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Set up environment
          command: |
            echo 'export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools' >> $BASH_ENV
            source $BASH_ENV
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle-
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - run:
          name: Assemble APK
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug
          destination: apks

  test:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/reports/tests/testDebugUnitTest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
